version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: ai_chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgresmps10
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    env_file:
      - .env

  db: 
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ai_chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgresmps10
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: